### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by DanForder** [JTDjan/Ticket-Tracker#1]
## Site

- Add your own [README.md](http://README.md) file, include a link to live site, screenshot etc.
- Looks great on all screen sizes, the card list is wrapping well, good work
- You've got it hosted and using GH Actions, awesome!
- Everything working as expected, and counters can't go lower than 0
- Remember to remove your console.logs when you clean up your code for production

## Code

- You have split up your solution into components and containers really well.
- You're almost there with BEM, remember to use *lower-case-hyphenated* and you'll be all set:

```jsx
//your code
className="employeeContainer__nameText"

// should be
className="employee-container__name-text"
```

- It's a tiny thing at the moment, but I would recommend adding an extension for formatting (I use 'Prettier') and using that by right clicking → format document. This will sort out all your indentation without you having to think about it. You can also configure it to format on save too which is awesome.
- Look for places you can reduce repetition with your stylings:

```scss
// your code
&__Title {
    text-align: center;
    background: transparent;
  }

&__Value {
  text-align: center;
  background: transparent;
}

// multiple classes
&__title, &__value {
  text-align: center;
  background: transparent;
}
```

- Overall I'm really impressed, this is looking great and there's not really anything major I would change with the React code.
